name: "Continuous Integration"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-linter:
    name: Python Linter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        name: Checking out repo
      - uses: "./.github/actions/setup_dependencies"
        name: Setting up dependencies
      - run: |
          uv sync
          uv run ruff check src/
          uv run ruff format --check src/
        name: Linting & Formating

  type-checker:
    name: Type Checker
    runs-on: ubuntu-24.04
    needs: python-linter
    steps:
      - uses: actions/checkout@v6
        name: Checking out repo
      - uses: "./.github/actions/setup_dependencies"
        name: Setting up dependencies
      - run: |
          uv sync
          uv run mypy src/
        name: Checking types

  tests-runner:
    name: Tests Runner
    needs: python-linter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        name: Checking out repo
      - uses: "./.github/actions/setup_dependencies"
        name: Setting up dependencies
      - run: |
          uv sync
          uv run pytest
        name: Running tests
