name: "Continuous Delivery"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Publish Version to PYPI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        name: Checking out repo
      - uses: "./.github/actions/setup_dependencies"
        name: Setting up dependencies
      - run: |
          uv build
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - uses: softprops/action-gh-release@v3
        name: Create GitHub Release
        with:
          generate-release-notes: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

